"""add github and coding profiles

Revision ID: 5e2b610b8372
Revises: 2645ecfeb61c
Create Date: 2026-06-15 23:49:03.014540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2b610b8372'
down_revision: Union[str, Sequence[str], None] = '2645ecfeb61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('max_rating', sa.Float(), nullable=True),
    sa.Column('ranking', sa.String(length=200), nullable=True),
    sa.Column('achievement_summary', sa.Text(), nullable=True),
    sa.Column('statistics', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_profiles_id'), 'coding_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_coding_profiles_platform'), 'coding_profiles', ['platform'], unique=True)
    op.create_table('github_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('blog_url', sa.String(length=500), nullable=True),
    sa.Column('followers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('following', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('public_repos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_stars', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_forks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('top_languages', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_profiles_github_user_id'), 'github_profiles', ['github_user_id'], unique=True)
    op.create_index(op.f('ix_github_profiles_id'), 'github_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_github_profiles_username'), 'github_profiles', ['username'], unique=True)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_profile_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('topics', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('stars_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('forks_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_fork', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['github_profile_id'], ['github_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repositories_github_profile_id'), 'github_repositories', ['github_profile_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_profile_id'), table_name='github_repositories')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_github_profiles_username'), table_name='github_profiles')
    op.drop_index(op.f('ix_github_profiles_id'), table_name='github_profiles')
    op.drop_index(op.f('ix_github_profiles_github_user_id'), table_name='github_profiles')
    op.drop_table('github_profiles')
    op.drop_index(op.f('ix_coding_profiles_platform'), table_name='coding_profiles')
    op.drop_index(op.f('ix_coding_profiles_id'), table_name='coding_profiles')
    op.drop_table('coding_profiles')
    # ### end Alembic commands ###
