"""add communication and analytics

Revision ID: 69bd4dd9faea
Revises: 5e2b610b8372
Create Date: 2026-06-16 00:24:03.965193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bd4dd9faea'
down_revision: Union[str, Sequence[str], None] = '5e2b610b8372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_table('interview_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('preferred_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('meeting_mode', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_requests_created_at'), 'interview_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_requests_email'), 'interview_requests', ['email'], unique=False)
    op.create_index(op.f('ix_interview_requests_id'), 'interview_requests', ['id'], unique=False)
    op.create_index(op.f('ix_interview_requests_status'), 'interview_requests', ['status'], unique=False)
    op.create_table('site_visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_key', sa.String(length=36), nullable=False),
    sa.Column('total_page_views', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visitors_id'), 'site_visitors', ['id'], unique=False)
    op.create_index(op.f('ix_site_visitors_last_seen_at'), 'site_visitors', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_site_visitors_visitor_key'), 'site_visitors', ['visitor_key'], unique=True)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('page_path', sa.String(length=300), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['site_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    op.create_index(op.f('ix_page_views_page_path'), 'page_views', ['page_path'], unique=False)
    op.create_index(op.f('ix_page_views_viewed_at'), 'page_views', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_page_views_visitor_id'), 'page_views', ['visitor_id'], unique=False)
    op.add_column('projects', sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'view_count')
    op.drop_index(op.f('ix_page_views_visitor_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_viewed_at'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_page_path'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_site_visitors_visitor_key'), table_name='site_visitors')
    op.drop_index(op.f('ix_site_visitors_last_seen_at'), table_name='site_visitors')
    op.drop_index(op.f('ix_site_visitors_id'), table_name='site_visitors')
    op.drop_table('site_visitors')
    op.drop_index(op.f('ix_interview_requests_status'), table_name='interview_requests')
    op.drop_index(op.f('ix_interview_requests_id'), table_name='interview_requests')
    op.drop_index(op.f('ix_interview_requests_email'), table_name='interview_requests')
    op.drop_index(op.f('ix_interview_requests_created_at'), table_name='interview_requests')
    op.drop_table('interview_requests')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
