"""add portfolio chatbot interactions

Revision ID: a17b59b48951
Revises: bd5bc1607290
Create Date: 2026-06-16 09:11:47.746513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17b59b48951'
down_revision: Union[str, Sequence[str], None] = 'bd5bc1607290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_key', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_refs', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('grounded', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('retrieval_method', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_interactions_created_at'), 'chat_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_interactions_id'), 'chat_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_interactions_visitor_key'), 'chat_interactions', ['visitor_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_interactions_visitor_key'), table_name='chat_interactions')
    op.drop_index(op.f('ix_chat_interactions_id'), table_name='chat_interactions')
    op.drop_index(op.f('ix_chat_interactions_created_at'), table_name='chat_interactions')
    op.drop_table('chat_interactions')
    # ### end Alembic commands ###
