"""add job match analyses

Revision ID: bd5bc1607290
Revises: 69bd4dd9faea
Create Date: 2026-06-16 01:14:25.215707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5bc1607290'
down_revision: Union[str, Sequence[str], None] = '69bd4dd9faea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_match_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=250), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('job_description_hash', sa.String(length=64), nullable=False),
    sa.Column('overall_match_score', sa.Float(), nullable=False),
    sa.Column('match_level', sa.String(length=50), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('recommended_resume_type', sa.String(length=80), nullable=False),
    sa.Column('embedding_method', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_analyses_created_at'), 'job_match_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_match_analyses_id'), 'job_match_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_job_match_analyses_job_description_hash'), 'job_match_analyses', ['job_description_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_match_analyses_job_description_hash'), table_name='job_match_analyses')
    op.drop_index(op.f('ix_job_match_analyses_id'), table_name='job_match_analyses')
    op.drop_index(op.f('ix_job_match_analyses_created_at'), table_name='job_match_analyses')
    op.drop_table('job_match_analyses')
    # ### end Alembic commands ###
