import type {
  AdminResourceConfig,
} from "../types/contentAdmin";

export const profileResource: AdminResourceConfig = {
  key: "profile",
  label: "Professional Profile",
  singularLabel: "Profile",
  endpoint: "/api/v1/profile",
  titleField: "full_name",
  subtitleField: "headline",
  fields: [
    {
      name: "full_name",
      label: "Full Name",
      type: "text",
      required: true,
    },
    {
      name: "headline",
      label: "Professional Headline",
      type: "text",
      required: true,
    },
    {
      name: "short_bio",
      label: "Short Biography",
      type: "textarea",
      required: true,
      rows: 4,
    },
    {
      name: "about_me",
      label: "About Me",
      type: "textarea",
      required: true,
      rows: 8,
    },
    {
      name: "email",
      label: "Email",
      type: "text",
      required: true,
    },
    {
      name: "phone",
      label: "Phone",
      type: "text",
    },
    {
      name: "location",
      label: "Location",
      type: "text",
    },
    {
      name: "profile_image_url",
      label: "Profile Image URL",
      type: "url",
    },
    {
      name: "linkedin_url",
      label: "LinkedIn URL",
      type: "url",
    },
    {
      name: "github_url",
      label: "GitHub URL",
      type: "url",
    },
    {
      name: "leetcode_url",
      label: "LeetCode URL",
      type: "url",
    },
    {
      name: "codechef_url",
      label: "CodeChef URL",
      type: "url",
    },
    {
      name: "years_experience",
      label: "Years of Experience",
      type: "number",
      required: true,
      min: 0,
      max: 60,
    },
  ],
};

export const contentResources: AdminResourceConfig[] = [
  {
    key: "education",
    label: "Education",
    singularLabel: "Education Record",
    endpoint: "/api/v1/education",
    titleField: "degree",
    subtitleField: "institution",
    fields: [
      {
        name: "institution",
        label: "Institution",
        type: "text",
        required: true,
      },
      {
        name: "degree",
        label: "Degree",
        type: "text",
        required: true,
      },
      {
        name: "field_of_study",
        label: "Field of Study",
        type: "text",
        required: true,
      },
      {
        name: "start_date",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        name: "end_date",
        label: "End Date",
        type: "date",
      },
      {
        name: "grade",
        label: "Grade",
        type: "text",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        rows: 5,
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "experiences",
    label: "Work Experience",
    singularLabel: "Experience",
    endpoint: "/api/v1/experiences",
    titleField: "job_title",
    subtitleField: "organization",
    fields: [
      {
        name: "organization",
        label: "Organization",
        type: "text",
        required: true,
      },
      {
        name: "job_title",
        label: "Job Title",
        type: "text",
        required: true,
      },
      {
        name: "employment_type",
        label: "Employment Type",
        type: "text",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
      },
      {
        name: "start_date",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        name: "end_date",
        label: "End Date",
        type: "date",
      },
      {
        name: "is_current",
        label: "Current Position",
        type: "checkbox",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        rows: 7,
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "skills",
    label: "Technical Skills",
    singularLabel: "Skill",
    endpoint: "/api/v1/skills",
    titleField: "name",
    subtitleField: "category",
    fields: [
      {
        name: "name",
        label: "Skill Name",
        type: "text",
        required: true,
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        required: true,
      },
      {
        name: "proficiency",
        label: "Proficiency",
        type: "number",
        required: true,
        min: 0,
        max: 100,
      },
      {
        name: "icon_name",
        label: "Icon Name",
        type: "text",
      },
      {
        name: "is_featured",
        label: "Featured Skill",
        type: "checkbox",
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "achievements",
    label: "Achievements",
    singularLabel: "Achievement",
    endpoint: "/api/v1/achievements",
    titleField: "title",
    subtitleField: "issuer",
    fields: [
      {
        name: "title",
        label: "Achievement Title",
        type: "text",
        required: true,
      },
      {
        name: "issuer",
        label: "Issuer",
        type: "text",
      },
      {
        name: "achievement_date",
        label: "Achievement Date",
        type: "date",
      },
      {
        name: "result",
        label: "Result",
        type: "text",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        rows: 5,
      },
      {
        name: "proof_url",
        label: "Proof URL",
        type: "url",
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "certifications",
    label: "Certifications",
    singularLabel: "Certification",
    endpoint: "/api/v1/certifications",
    titleField: "name",
    subtitleField: "issuer",
    fields: [
      {
        name: "name",
        label: "Certification Name",
        type: "text",
        required: true,
      },
      {
        name: "issuer",
        label: "Issuer",
        type: "text",
        required: true,
      },
      {
        name: "issue_date",
        label: "Issue Date",
        type: "date",
      },
      {
        name: "expiration_date",
        label: "Expiration Date",
        type: "date",
      },
      {
        name: "credential_id",
        label: "Credential ID",
        type: "text",
      },
      {
        name: "credential_url",
        label: "Credential URL",
        type: "url",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        rows: 5,
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "projects",
    label: "Projects",
    singularLabel: "Project",
    endpoint: "/api/v1/projects",
    titleField: "title",
    subtitleField: "category",
    fields: [
      {
        name: "title",
        label: "Project Title",
        type: "text",
        required: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        required: true,
        placeholder: "recruitai-pro",
      },
      {
        name: "category",
        label: "Category",
        type: "text",
        required: true,
      },
      {
        name: "short_description",
        label: "Short Description",
        type: "textarea",
        required: true,
        rows: 3,
      },
      {
        name: "description",
        label: "Complete Description",
        type: "textarea",
        required: true,
        rows: 9,
      },
      {
        name: "tech_stack",
        label: "Technology Stack",
        type: "tags",
        placeholder: "Python, FastAPI, React, PostgreSQL",
      },
      {
        name: "github_url",
        label: "GitHub URL",
        type: "url",
      },
      {
        name: "live_demo_url",
        label: "Live Demo URL",
        type: "url",
      },
      {
        name: "challenges",
        label: "Challenges",
        type: "textarea",
        rows: 5,
      },
      {
        name: "solutions",
        label: "Solutions",
        type: "textarea",
        rows: 5,
      },
      {
        name: "results",
        label: "Results",
        type: "textarea",
        rows: 5,
      },
      {
        name: "is_featured",
        label: "Featured Project",
        type: "checkbox",
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "research",
    label: "Research",
    singularLabel: "Research Record",
    endpoint: "/api/v1/research",
    titleField: "title",
    subtitleField: "research_type",
    fields: [
      {
        name: "title",
        label: "Research Title",
        type: "text",
        required: true,
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        required: true,
      },
      {
        name: "research_type",
        label: "Research Type",
        type: "text",
        required: true,
      },
      {
        name: "short_summary",
        label: "Short Summary",
        type: "textarea",
        required: true,
        rows: 4,
      },
      {
        name: "abstract",
        label: "Abstract",
        type: "textarea",
        required: true,
        rows: 10,
      },
      {
        name: "dataset_details",
        label: "Dataset Details",
        type: "textarea",
        rows: 6,
      },
      {
        name: "methodology",
        label: "Methodology",
        type: "textarea",
        rows: 7,
      },
      {
        name: "models_used",
        label: "Models Used",
        type: "tags",
        placeholder: "LSTM, BiLSTM",
      },
      {
        name: "metrics",
        label: "Metrics JSON",
        type: "json",
        placeholder:
          '{"LSTM Macro F1": 76.2, "BiLSTM Macro F1": 79.3}',
      },
      {
        name: "publication_status",
        label: "Publication Status",
        type: "text",
        required: true,
      },
      {
        name: "publication_date",
        label: "Publication Date",
        type: "date",
      },
      {
        name: "venue",
        label: "Venue",
        type: "text",
      },
      {
        name: "paper_url",
        label: "Paper URL",
        type: "url",
      },
      {
        name: "thesis_url",
        label: "Thesis URL",
        type: "url",
      },
      {
        name: "code_url",
        label: "Code URL",
        type: "url",
      },
      {
        name: "is_featured",
        label: "Featured Research",
        type: "checkbox",
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
  {
    key: "codingProfiles",
    label: "Coding Profiles",
    singularLabel: "Coding Profile",
    endpoint: "/api/v1/coding-profiles",
    titleField: "display_name",
    subtitleField: "platform",
    fields: [
      {
        name: "platform",
        label: "Platform",
        type: "text",
        required: true,
        placeholder: "leetcode",
      },
      {
        name: "username",
        label: "Username",
        type: "text",
      },
      {
        name: "display_name",
        label: "Display Name",
        type: "text",
        required: true,
      },
      {
        name: "profile_url",
        label: "Profile URL",
        type: "url",
      },
      {
        name: "total_solved",
        label: "Total Problems Solved",
        type: "number",
        min: 0,
      },
      {
        name: "rating",
        label: "Current Rating",
        type: "number",
        min: 0,
      },
      {
        name: "max_rating",
        label: "Maximum Rating",
        type: "number",
        min: 0,
      },
      {
        name: "ranking",
        label: "Ranking",
        type: "text",
      },
      {
        name: "achievement_summary",
        label: "Achievement Summary",
        type: "textarea",
        rows: 5,
      },
      {
        name: "statistics",
        label: "Statistics JSON",
        type: "json",
        placeholder:
          '{"problems_solved": "300+", "contest_rank": 783}',
      },
      {
        name: "display_order",
        label: "Display Order",
        type: "number",
        min: 0,
      },
      {
        name: "is_visible",
        label: "Visible",
        type: "checkbox",
      },
    ],
  },
];